import HomePanel from "@/components/HomePanel";
import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Admin Panel",
	description: "Generated by create next app",
};

export default async function HomePanelPage() {
	return <HomePanel />;
}
