import { DncommerceApiClient as API } from "@/services/dncommerce-api";
import { Metadata } from "next";
import UserInventory from "@/components/UserInventory";

export const metadata: Metadata = {
	title: "Panel - Users",
	description: "Generated by create next app",
};

export default async function ProductsPanel() {
	const users = await API.Users.Instance().get();

	return <UserInventory initialData={users} />;
}
