import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Panel - Users",
	description: "Generated by create next app",
};

export default function ProductsPanel() {
	return (
		<>
			<p>Painel de usuarios</p>
		</>
	);
}
