import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import SidePanel from "@/components/SidePanel/SidePanel";
import isAuthenticated from "@/utils/isAuthenticated";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const auth = await isAuthenticated();
	if (auth.status === false) redirect("/login");

	return (
		<html lang="pt-br">
			<body className={`${inter.className} flex bg-zinc-50`}>
				<div className="z-50 mr-64 sm:mr-0">
					<SidePanel userId={auth.userId} username={auth.username} />
				</div>
				<div id={"panelContent"} className="w-full overflow-auto">
					{children}
				</div>
			</body>
		</html>
	);
}
