import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import SidePanel from "@/components/SidePanel/SidePanel";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="pt-br">
			<body className={`${inter.className} flex`}>
				<div className="z-50 w-full">
					<SidePanel />
				</div>
				<div id={"panelContent"} className="w-full">
					{children}
				</div>
			</body>
		</html>
	);
}
