import "../globals.css";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
	icons: {
		icon: "/png/login-favicon.png",
	},
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="pt-br">
			<body>{children}</body>
		</html>
	);
}
