import { Metadata } from "next";
import Login from "@/components/Login/Login";
import axios from "axios";
import { redirect } from "next/navigation";
import { headers } from "next/headers";

export const metadata: Metadata = {
	title: "Login",
	description: "Generated by create next app",
};

export default async function LoginPage() {
	const headersList = headers();
	const host = headersList.get("host");

	const { data } = await axios.get(`http://${host}/api/login`); // check if user is logged
	if (data.sucess) redirect("/panel");

	return <Login />;
}
