import { DncommerceApiClient as API } from "@/services/dncommerce-api";
import { Metadata } from "next";
import ProductInventory from "../../../../components/ProductInventory";

export const metadata: Metadata = {
	title: "Panel - Products",
	description: "Generated by create next app",
};

export default async function ProductsPanel() {
	const products = await API.Products.Instance().get();
	return <ProductInventory data={products} />;
}
