import ProductInventory from "@/components/ProductInventory";
import { DncommerceApiClient as API } from "@/services/dncommerce-api";
import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Panel - Products",
	description: "Generated by create next app",
};

export default async function ProductsPanelPage() {
	const products = await API.Products.Instance().get();

	return <ProductInventory initialData={products} />;
}
