import ProductInventory from "@/components/ProductInventory";
import { DncommerceApiClient as API } from "@/services/dncommerce-api";
import { Metadata } from "next";
import { cookies } from "next/headers";

export const metadata: Metadata = {
	title: "Panel - Products",
	description: "Generated by create next app",
};

export default async function ProductsPanelPage() {
	const token = cookies().get("token")?.value || "";
	const products = await API.Products.Instance().get(token);

	return <ProductInventory initialData={products} />;
}
